# docker-compose.yml
services:
  # === Banco ===
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # === Broker de eventos (NATS) ===
  nats:
    image: nats:2
    command: ["-js"]           # (opcional) JetStream ligado
    ports:
      - "4222:4222"            # client
      - "8222:8222"            # monitoring
    restart: unless-stopped

  # === Serviço Movies (gRPC) ===
  movies:
    build:
      context: .                          # raiz do repo
      dockerfile: deploy/docker/movies.Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongo:27017/moviesdb
      - MONGODB_DB=moviesdb
      - GRPC_PORT=50051
      - SEED_FILE=/app/seed/movies.json   # o Dockerfile copia esse arquivo para /app/seed
      # ---- Eventos (NATS) ----
      - NATS_ENABLED=true
      - NATS_URL=nats://nats:4222
      - NATS_SUBJECT_CREATED=movies.created
      - NATS_SUBJECT_DELETED=movies.deleted
    depends_on:
      - mongo
      - nats
    ports:
      - "50051:50051"
    restart: unless-stopped

  # === API Gateway (HTTP/Swagger) ===
  api-gateway:
    build:
      context: .                          # raiz do repo
      dockerfile: deploy/docker/api.Dockerfile
    environment:
      - MOVIES_ADDR=movies:50051          # endereço do gRPC interno
      # (opcional) override do host do Swagger:
      # - SWAGGER_HOST=localhost:8080
    depends_on:
      - movies
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mongo_data:
