// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: moviespb/movies.proto

package moviespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Movie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Director      string                 `protobuf:"bytes,3,opt,name=director,proto3" json:"director,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Genre         string                 `protobuf:"bytes,5,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movie) Reset() {
	*x = Movie{}
	mi := &file_moviespb_movies_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movie) ProtoMessage() {}

func (x *Movie) ProtoReflect() protoreflect.Message {
	mi := &file_moviespb_movies_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movie.ProtoReflect.Descriptor instead.
func (*Movie) Descriptor() ([]byte, []int) {
	return file_moviespb_movies_proto_rawDescGZIP(), []int{0}
}

func (x *Movie) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Movie) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movie) GetDirector() string {
	if x != nil {
		return x.Director
	}
	return ""
}

func (x *Movie) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Movie) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type ListMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movie               `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMoviesResponse) Reset() {
	*x = ListMoviesResponse{}
	mi := &file_moviespb_movies_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMoviesResponse) ProtoMessage() {}

func (x *ListMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviespb_movies_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMoviesResponse.ProtoReflect.Descriptor instead.
func (*ListMoviesResponse) Descriptor() ([]byte, []int) {
	return file_moviespb_movies_proto_rawDescGZIP(), []int{1}
}

func (x *ListMoviesResponse) GetMovies() []*Movie {
	if x != nil {
		return x.Movies
	}
	return nil
}

type GetMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieRequest) Reset() {
	*x = GetMovieRequest{}
	mi := &file_moviespb_movies_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRequest) ProtoMessage() {}

func (x *GetMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviespb_movies_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRequest.ProtoReflect.Descriptor instead.
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return file_moviespb_movies_proto_rawDescGZIP(), []int{2}
}

func (x *GetMovieRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieResponse) Reset() {
	*x = GetMovieResponse{}
	mi := &file_moviespb_movies_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieResponse) ProtoMessage() {}

func (x *GetMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviespb_movies_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieResponse.ProtoReflect.Descriptor instead.
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return file_moviespb_movies_proto_rawDescGZIP(), []int{3}
}

func (x *GetMovieResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type CreateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Director      string                 `protobuf:"bytes,2,opt,name=director,proto3" json:"director,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Genre         string                 `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieRequest) Reset() {
	*x = CreateMovieRequest{}
	mi := &file_moviespb_movies_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieRequest) ProtoMessage() {}

func (x *CreateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviespb_movies_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieRequest.ProtoReflect.Descriptor instead.
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return file_moviespb_movies_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMovieRequest) GetDirector() string {
	if x != nil {
		return x.Director
	}
	return ""
}

func (x *CreateMovieRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateMovieRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

type CreateMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         *Movie                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieResponse) Reset() {
	*x = CreateMovieResponse{}
	mi := &file_moviespb_movies_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieResponse) ProtoMessage() {}

func (x *CreateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviespb_movies_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieResponse.ProtoReflect.Descriptor instead.
func (*CreateMovieResponse) Descriptor() ([]byte, []int) {
	return file_moviespb_movies_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMovieResponse) GetMovie() *Movie {
	if x != nil {
		return x.Movie
	}
	return nil
}

type DeleteMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieRequest) Reset() {
	*x = DeleteMovieRequest{}
	mi := &file_moviespb_movies_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieRequest) ProtoMessage() {}

func (x *DeleteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moviespb_movies_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieRequest.ProtoReflect.Descriptor instead.
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return file_moviespb_movies_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMovieRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieResponse) Reset() {
	*x = DeleteMovieResponse{}
	mi := &file_moviespb_movies_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieResponse) ProtoMessage() {}

func (x *DeleteMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moviespb_movies_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieResponse.ProtoReflect.Descriptor instead.
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return file_moviespb_movies_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMovieResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_moviespb_movies_proto protoreflect.FileDescriptor

const file_moviespb_movies_proto_rawDesc = "" +
	"\n" +
	"\x15moviespb/movies.proto\x12\bmoviespb\x1a\x1bgoogle/protobuf/empty.proto\"s\n" +
	"\x05Movie\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bdirector\x18\x03 \x01(\tR\bdirector\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05genre\x18\x05 \x01(\tR\x05genre\"=\n" +
	"\x12ListMoviesResponse\x12'\n" +
	"\x06movies\x18\x01 \x03(\v2\x0f.moviespb.MovieR\x06movies\"!\n" +
	"\x0fGetMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10GetMovieResponse\x12%\n" +
	"\x05movie\x18\x01 \x01(\v2\x0f.moviespb.MovieR\x05movie\"p\n" +
	"\x12CreateMovieRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bdirector\x18\x02 \x01(\tR\bdirector\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x14\n" +
	"\x05genre\x18\x04 \x01(\tR\x05genre\"<\n" +
	"\x13CreateMovieResponse\x12%\n" +
	"\x05movie\x18\x01 \x01(\v2\x0f.moviespb.MovieR\x05movie\"$\n" +
	"\x12DeleteMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteMovieResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xad\x02\n" +
	"\fMovieService\x12B\n" +
	"\n" +
	"ListMovies\x12\x16.google.protobuf.Empty\x1a\x1c.moviespb.ListMoviesResponse\x12A\n" +
	"\bGetMovie\x12\x19.moviespb.GetMovieRequest\x1a\x1a.moviespb.GetMovieResponse\x12J\n" +
	"\vCreateMovie\x12\x1c.moviespb.CreateMovieRequest\x1a\x1d.moviespb.CreateMovieResponse\x12J\n" +
	"\vDeleteMovie\x12\x1c.moviespb.DeleteMovieRequest\x1a\x1d.moviespb.DeleteMovieResponseB>Z<github.com/caiqueborghese/sipubtech-challenge/proto/moviespbb\x06proto3"

var (
	file_moviespb_movies_proto_rawDescOnce sync.Once
	file_moviespb_movies_proto_rawDescData []byte
)

func file_moviespb_movies_proto_rawDescGZIP() []byte {
	file_moviespb_movies_proto_rawDescOnce.Do(func() {
		file_moviespb_movies_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moviespb_movies_proto_rawDesc), len(file_moviespb_movies_proto_rawDesc)))
	})
	return file_moviespb_movies_proto_rawDescData
}

var file_moviespb_movies_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_moviespb_movies_proto_goTypes = []any{
	(*Movie)(nil),               // 0: moviespb.Movie
	(*ListMoviesResponse)(nil),  // 1: moviespb.ListMoviesResponse
	(*GetMovieRequest)(nil),     // 2: moviespb.GetMovieRequest
	(*GetMovieResponse)(nil),    // 3: moviespb.GetMovieResponse
	(*CreateMovieRequest)(nil),  // 4: moviespb.CreateMovieRequest
	(*CreateMovieResponse)(nil), // 5: moviespb.CreateMovieResponse
	(*DeleteMovieRequest)(nil),  // 6: moviespb.DeleteMovieRequest
	(*DeleteMovieResponse)(nil), // 7: moviespb.DeleteMovieResponse
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_moviespb_movies_proto_depIdxs = []int32{
	0, // 0: moviespb.ListMoviesResponse.movies:type_name -> moviespb.Movie
	0, // 1: moviespb.GetMovieResponse.movie:type_name -> moviespb.Movie
	0, // 2: moviespb.CreateMovieResponse.movie:type_name -> moviespb.Movie
	8, // 3: moviespb.MovieService.ListMovies:input_type -> google.protobuf.Empty
	2, // 4: moviespb.MovieService.GetMovie:input_type -> moviespb.GetMovieRequest
	4, // 5: moviespb.MovieService.CreateMovie:input_type -> moviespb.CreateMovieRequest
	6, // 6: moviespb.MovieService.DeleteMovie:input_type -> moviespb.DeleteMovieRequest
	1, // 7: moviespb.MovieService.ListMovies:output_type -> moviespb.ListMoviesResponse
	3, // 8: moviespb.MovieService.GetMovie:output_type -> moviespb.GetMovieResponse
	5, // 9: moviespb.MovieService.CreateMovie:output_type -> moviespb.CreateMovieResponse
	7, // 10: moviespb.MovieService.DeleteMovie:output_type -> moviespb.DeleteMovieResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_moviespb_movies_proto_init() }
func file_moviespb_movies_proto_init() {
	if File_moviespb_movies_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moviespb_movies_proto_rawDesc), len(file_moviespb_movies_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moviespb_movies_proto_goTypes,
		DependencyIndexes: file_moviespb_movies_proto_depIdxs,
		MessageInfos:      file_moviespb_movies_proto_msgTypes,
	}.Build()
	File_moviespb_movies_proto = out.File
	file_moviespb_movies_proto_goTypes = nil
	file_moviespb_movies_proto_depIdxs = nil
}
